/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2015, xuewen.chu
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of xuewen.chu nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL xuewen.chu BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

#include "qgr/js/qgr.h"
#include "qgr/media-codec.h"

/**
 * @ns qgr::js
 */

JS_BEGIN

void binding_audio(Local<JSObject> exports, Worker* worker);
void binding_video(Local<JSObject> exports, Worker* worker);

/**
 * @class NativeMedia
 */
class NativeMedia {
 public:
  static void binding(Local<JSObject> exports, Worker* worker) {
	if ( !initialize_media() )
		JS_THROW_ERR("binding or initialize media library fail");

	JS_SET_PROPERTY(MEDIA_TYPE_AUDIO, MEDIA_TYPE_AUDIO);
	JS_SET_PROPERTY(MEDIA_TYPE_VIDEO, MEDIA_TYPE_VIDEO);
	//
	JS_SET_PROPERTY(PLAYER_STATUS_STOP, PLAYER_STATUS_STOP);
	JS_SET_PROPERTY(PLAYER_STATUS_START, PLAYER_STATUS_START);
	JS_SET_PROPERTY(PLAYER_STATUS_PLAYING, PLAYER_STATUS_PLAYING);
	JS_SET_PROPERTY(PLAYER_STATUS_PAUSED, PLAYER_STATUS_PAUSED);
	//
	JS_SET_PROPERTY(MULTIMEDIA_SOURCE_STATUS_UNINITIALIZED, MULTIMEDIA_SOURCE_STATUS_UNINITIALIZED);
	JS_SET_PROPERTY(MULTIMEDIA_SOURCE_STATUS_READYING, MULTIMEDIA_SOURCE_STATUS_READYING);
	JS_SET_PROPERTY(MULTIMEDIA_SOURCE_STATUS_READY, MULTIMEDIA_SOURCE_STATUS_READY);
	JS_SET_PROPERTY(MULTIMEDIA_SOURCE_STATUS_WAIT, MULTIMEDIA_SOURCE_STATUS_WAIT);
	JS_SET_PROPERTY(MULTIMEDIA_SOURCE_STATUS_FAULT, MULTIMEDIA_SOURCE_STATUS_FAULT);
	JS_SET_PROPERTY(MULTIMEDIA_SOURCE_STATUS_EOF, MULTIMEDIA_SOURCE_STATUS_EOF);
	//
	JS_SET_PROPERTY(VIDEO_COLOR_FORMAT_INVALID, VIDEO_COLOR_FORMAT_INVALID);
	JS_SET_PROPERTY(VIDEO_COLOR_FORMAT_YUV420P, VIDEO_COLOR_FORMAT_YUV420P);
	JS_SET_PROPERTY(VIDEO_COLOR_FORMAT_YUV420SP, VIDEO_COLOR_FORMAT_YUV420SP);
	JS_SET_PROPERTY(VIDEO_COLOR_FORMAT_YUV411P, VIDEO_COLOR_FORMAT_YUV411P);
	JS_SET_PROPERTY(VIDEO_COLOR_FORMAT_YUV411SP, VIDEO_COLOR_FORMAT_YUV411SP);
	//
	JS_SET_PROPERTY(CH_INVALID, CH_INVALID);
	JS_SET_PROPERTY(CH_FRONT_LEFT, CH_FRONT_LEFT);
	JS_SET_PROPERTY(CH_FRONT_RIGHT, CH_FRONT_RIGHT);
	JS_SET_PROPERTY(CH_FRONT_CENTER, CH_FRONT_CENTER);
	JS_SET_PROPERTY(CH_LOW_FREQUENCY, CH_LOW_FREQUENCY);
	JS_SET_PROPERTY(CH_BACK_LEFT, CH_BACK_LEFT);
	JS_SET_PROPERTY(CH_BACK_RIGHT, CH_BACK_RIGHT);
	JS_SET_PROPERTY(CH_FRONT_LEFT_OF_CENTER, CH_FRONT_LEFT_OF_CENTER);
	JS_SET_PROPERTY(CH_FRONT_RIGHT_OF_CENTER, CH_FRONT_RIGHT_OF_CENTER);
	JS_SET_PROPERTY(CH_BACK_CENTER, CH_BACK_CENTER);
	JS_SET_PROPERTY(CH_SIDE_LEFT, CH_SIDE_LEFT);
	JS_SET_PROPERTY(CH_SIDE_RIGHT, CH_SIDE_RIGHT);
	JS_SET_PROPERTY(CH_TOP_CENTER, CH_TOP_CENTER);
	JS_SET_PROPERTY(CH_TOP_FRONT_LEFT, CH_TOP_FRONT_LEFT);
	JS_SET_PROPERTY(CH_TOP_FRONT_CENTER, CH_TOP_FRONT_CENTER);
	JS_SET_PROPERTY(CH_TOP_FRONT_RIGHT, CH_TOP_FRONT_RIGHT);
	JS_SET_PROPERTY(CH_TOP_BACK_LEFT, CH_TOP_BACK_LEFT);
	JS_SET_PROPERTY(CH_TOP_BACK_CENTER, CH_TOP_BACK_CENTER);
	JS_SET_PROPERTY(CH_TOP_BACK_RIGHT, CH_TOP_BACK_RIGHT);

	binding_audio(exports, worker);
	binding_video(exports, worker);
  }
};


JS_REG_MODULE(_media, NativeMedia);
JS_END
