#!/bin/sh
#/Users/louis/install/dev/android-sdk/ndk-bundle
 
base=$(dirname "$0")
cd $base

ndk=$ANDROID_HOME/ndk-bundle
level="21"
arch="arm"
dir="arm"
toolchain="arm-linux-androideabi-4.9"

if [ $1 ]; then
	ndk=$1
fi

if [ ! -d $ndk ]; then
	echo No ndk directory " ./tools/install-android-toolchain [NDK-DIR] [level] [arm|arm64|mips|mips64|x86|x64]"
	exit 1
fi

if [ $2 ]; then
	level=$2
fi

p3="$3"

if [ "$3" = "arm64" ]; then
	arch="arm64"
	dir="arm64"
	toolchain="aarch64-linux-android-4.9"
elif [ "$3" = "mips" ]; then
	arch="mips"
	dir="mips"
	toolchain="mipsel-linux-android-4.9"
elif [ "$3" = "mips64" ]; then
	arch="mips64"
	dir="mips64"
	toolchain="mips64el-linux-android-4.9"
elif [ "$3" = "x86" ] || [ "$3" = "ia32" ] || [ "$3" = "i386" ]; then
	arch="x86"
	dir="x86"
	toolchain="x86-4.9"
elif [ "$3" = "x64" ] || [ "$3" = "x86_64" ] || [ "$3" = "ia64" ]; then
	arch="x86_64"
	dir="x64"
	toolchain="x86_64-4.9"
fi

echo $ndk, $level, $arch, $toolchain

DIR=$PWD/android-toolchain/$dir

if [ ! -f $DIR/bin/clang ]; then

	$ndk/build/tools/make-standalone-toolchain.sh \
		--toolchain=$toolchain \
		--install-dir=$DIR \
		--platform=android-$level \
		--arch=$arch \
		--force
	
	if [ `which python` ]; then 
	 rm -rf $DIR/bin/python
	fi
fi